spring:
  application:
    name: productsapi
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:productsdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui
